# Generated by Django 5.1.3 on 2026-06-09 07:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImportBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=255)),
                ('imported_at', models.DateTimeField(auto_now_add=True)),
                ('total_records', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'import_batches',
            },
        ),
        migrations.CreateModel(
            name='WorkOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wo_code', models.CharField(max_length=100, unique=True)),
                ('work_type', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'work_orders',
            },
        ),
        migrations.CreateModel(
            name='WorkOrderSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(blank=True, max_length=100, null=True)),
                ('system_name', models.CharField(blank=True, max_length=100, null=True)),
                ('priority_level', models.CharField(blank=True, max_length=100, null=True)),
                ('province_code', models.CharField(blank=True, max_length=50, null=True)),
                ('district_name', models.CharField(blank=True, max_length=255, null=True)),
                ('wo_group', models.CharField(blank=True, max_length=100, null=True)),
                ('dispatch_group', models.CharField(blank=True, max_length=255, null=True)),
                ('creator', models.CharField(blank=True, max_length=255, null=True)),
                ('assignee', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('due_at', models.DateTimeField(blank=True, null=True)),
                ('overdue_days', models.IntegerField(blank=True, null=True)),
                ('penalty_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='api.importbatch')),
                ('work_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='api.workorder')),
            ],
            options={
                'db_table': 'work_order_snapshots',
            },
        ),
    ]
