# Generated by Django 5.1.3 on 2026-06-11 04:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImportBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=255)),
                ('imported_at', models.DateTimeField(auto_now_add=True)),
                ('total_records', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'import_batches',
            },
        ),
        migrations.CreateModel(
            name='WorkOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wo_code', models.CharField(db_index=True, max_length=100)),
                ('work_type', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(blank=True, max_length=100, null=True)),
                ('system_name', models.CharField(blank=True, max_length=100, null=True)),
                ('priority_level', models.CharField(blank=True, max_length=100, null=True)),
                ('province_code', models.CharField(blank=True, max_length=50, null=True)),
                ('district_code', models.CharField(blank=True, max_length=50, null=True)),
                ('district_name', models.CharField(blank=True, max_length=255, null=True)),
                ('area', models.CharField(blank=True, max_length=100, null=True)),
                ('station_code', models.CharField(blank=True, max_length=100, null=True)),
                ('wo_group', models.CharField(blank=True, max_length=100, null=True)),
                ('dispatch_group', models.CharField(blank=True, max_length=255, null=True)),
                ('creator', models.CharField(blank=True, max_length=255, null=True)),
                ('assignee', models.CharField(blank=True, max_length=255, null=True)),
                ('ft_comment', models.TextField(blank=True, null=True)),
                ('ft_phone', models.CharField(blank=True, max_length=30, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('due_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('remaining_hours', models.FloatField(blank=True, null=True)),
                ('overdue_days', models.IntegerField(blank=True, null=True)),
                ('penalty_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('work_content', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_orders', to='api.importbatch')),
            ],
            options={
                'db_table': 'work_orders',
                'indexes': [models.Index(fields=['status'], name='work_orders_status_3f6c76_idx'), models.Index(fields=['province_code'], name='work_orders_provinc_17b04b_idx'), models.Index(fields=['system_name'], name='work_orders_system__1c74c0_idx'), models.Index(fields=['priority_level'], name='work_orders_priorit_b4ff59_idx'), models.Index(fields=['created_at'], name='work_orders_created_5fb8d6_idx'), models.Index(fields=['due_at'], name='work_orders_due_at_cab8da_idx')],
            },
        ),
    ]
