# Generated by Django 5.1.3 on 2026-06-09 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workorder',
            name='work_type',
        ),
        migrations.AddField(
            model_name='workordersnapshot',
            name='area',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='workordersnapshot',
            name='closed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workordersnapshot',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workordersnapshot',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workordersnapshot',
            name='district_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='workordersnapshot',
            name='ft_comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workordersnapshot',
            name='ft_phone',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='workordersnapshot',
            name='remaining_hours',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workordersnapshot',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workordersnapshot',
            name='station_code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='workordersnapshot',
            name='work_content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workordersnapshot',
            name='work_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddIndex(
            model_name='workordersnapshot',
            index=models.Index(fields=['status'], name='work_order__status_ddae33_idx'),
        ),
        migrations.AddIndex(
            model_name='workordersnapshot',
            index=models.Index(fields=['province_code'], name='work_order__provinc_6ed942_idx'),
        ),
        migrations.AddIndex(
            model_name='workordersnapshot',
            index=models.Index(fields=['system_name'], name='work_order__system__64b623_idx'),
        ),
        migrations.AddIndex(
            model_name='workordersnapshot',
            index=models.Index(fields=['priority_level'], name='work_order__priorit_e126db_idx'),
        ),
        migrations.AddIndex(
            model_name='workordersnapshot',
            index=models.Index(fields=['created_at'], name='work_order__created_629541_idx'),
        ),
        migrations.AddIndex(
            model_name='workordersnapshot',
            index=models.Index(fields=['due_at'], name='work_order__due_at_b87bc8_idx'),
        ),
    ]
