# Generated by Django 5.1.3 on 2026-06-11 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DispatchAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('province_code', models.CharField(max_length=50)),
                ('ft_of', models.CharField(max_length=50)),
                ('dispatch_group', models.CharField(max_length=255)),
                ('creator', models.CharField(blank=True, max_length=255, null=True)),
                ('assignee', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'dispatch_assignments',
            },
        ),
    ]
