# Generated by Django 5.1.3 on 2026-06-11 15:48

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_dispatchassignment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dispatchassignment',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
