# Generated by Django 5.1.3 on 2026-06-14 12:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_dispatchassignment_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='FTProductivityDaily',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('daytime', models.DateField()),
                ('wo_done', models.IntegerField(default=0)),
                ('dispatch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_stats', to='api.dispatchassignment')),
            ],
            options={
                'db_table': 'ft_productivity_daily',
                'unique_together': {('dispatch', 'daytime')},
            },
        ),
    ]
