# Generated by Django 5.1.3 on 2026-06-14 13:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_ftproductivitydaily'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyProductivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('daytime', models.DateField(verbose_name='Ngày thực hiện')),
                ('wo_done', models.IntegerField(default=0, verbose_name='Số lượng WO hoàn thành')),
                ('assignee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productivities', to='api.dispatchassignment')),
            ],
            options={
                'db_table': 'daily_productivity',
                'unique_together': {('assignee', 'daytime')},
            },
        ),
        migrations.DeleteModel(
            name='FTProductivityDaily',
        ),
    ]
