# Generated by Django 5.1.3 on 2026-06-14 14:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_dailyproductivity_delete_ftproductivitydaily'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyproductivity',
            name='assignee',
            field=models.ForeignKey(db_column='assignee_id', on_delete=django.db.models.deletion.CASCADE, related_name='productivities', to='api.dispatchassignment'),
        ),
    ]
